sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.236.31.41
    port: 3306
    database: sky_take_out
    username: root
    password: 200046
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: cl-web
  wechat:
    appid: wx5f12612d7623c322
    secret: be71d49c24e777c01882f616e30743bd