sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.236.31.41
    port: 3306
    database: sky_take_out
    username: root
    password: 200046
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
  alioss:
    access-key-id: LTAI5tDFxe8gLUH9ms5XZ4z5
    access-key-secret: 1dj0iWeYQH2IaPNuURS943cN0xDyNi
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: cl-web
